apiVersion: apps/v1
kind: Deployment
metadata:
  name: musicschool-cml-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: musicschool-api
  template:
    metadata:
      labels:
        app: musicschool-api
    spec:
      containers:
      - name: musicschool-api-container
        image: gcr.io/musicschool-cml/musicschool-api
        ports:
        - containerPort: 8080
        env:
          - name: RECAPTCHA_SECRET
            valueFrom:
              secretKeyRef:
                name: recaptcha-secret
                key: RECAPTCHA_SECRET
          - name: RESEND_API_KEY
            valueFrom:
              secretKeyRef:
                name: resend-api-key
                key: RESEND_API_KEY
          - name: RESEND_RECEIVER
            valueFrom:
              secretKeyRef:
                name: resend-receiver
                key: RESEND_RECEIVER
