apiVersion: v1
kind: Service
metadata:
  name: musicschool-load-balancer
  annotations:
    cloud.google.com/load-balancer-type: "External"
spec:
  selector:
    app: musicschool-api
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8080
    - protocol: TCP
      name: https
      port: 443
      targetPort: 8080
  type: LoadBalancer
  loadBalancerIP: 34.19.103.158
