apiVersion: v1
kind: Service
metadata:
  name: musicschool-cml-service
spec:
  selector:
    app: musicschool-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
